### ISSUE TITLE
[BUG] : Colonization Fever tradition +1 building does not stack with planetary capital upgrades

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#82] opened 2019-11-16 19:37 UTC
The Expansion Tree Colonization Fever tradition unlocks 1 building which is fine, but when I upgraded the ship shelter to a Planetary Administration (5 pop capital) I did not get another building unlock.

**Comment by gebnar** [comment] 2019-11-17 03:59
This is the intended behavior. Localization will be changed to more clearly reflect this behavior.

Thanks for reporting this!

**Comment by Vstef** [comment] 2019-11-17 08:10
I see. Wouldn't this make upgrading to a 5 pop capital redundant? It would be more beneficial for single resource worlds to just wait it out until they hit 10 pops in order to have any more buildings, profiting from the increased pop growth via the colonist job until then.

**Comment by gebnar** [comment] 2019-11-17 14:44
It should be a trade-off. Ruler jobs are pretty powerful. But yeah, delaying the 5-pop upgrade to get more growth out of your colony is definitely an expansion-themed choice. Having the option to do so is intentional.

**Comment by gebnar** [comment] 2019-11-18 19:29
Should just need localization to be more clear. Hopefully.

**Comment by Metadig** [comment] 2019-12-12 16:04
This issue is being resolved with the tradition overhaul.

**Closed by Metadig** 2019-12-12 16:04 UTC
Labels: bug
