### ISSUE TITLE
Pops do not grow on newly colonized/frontier worlds.

### ISSUE THREAD

**Issue by Lexalopolis** [Stellaris-Immortal/retile#142] opened 2019-12-02 00:19 UTC
This bug primarily appears to happen on frontier worlds.  New pops will begin to grow, then at the end of the month all growth is erased and the pop disappears.  Trying to force a certain species/pop to grow does not work, the planet resets to growing any pop and erases all progress. Changing policies from Full Reproductive Rights to No Reproductive Rights had no effect.  Only newly colonized worlds appear to be effected, several planets colonized earlier in my current game are growing pops normally.  Robot production is unaffected.

**Comment by Lexalopolis** [comment] 2019-12-02 01:14
I was able to force my primary/founding species to grow and have seen sustained growth since then.  I am unable to grow a species that migrated to my empire, nor a species that I uplifted on frontier worlds/habitats.  However, my uplifted species is growing normally on other established planets in my empire.

**Comment by gebnar** [comment] 2019-12-03 17:55
Does the pop growth disappear when a robot is produced? Or is the growth just disappearing sporadically?

**Comment by Lexalopolis** [comment] 2019-12-03 18:04
Robot pops are unaffected and grow normally, both on my more established worlds and new colonies.  I haven't noticed an interaction between the growth of robot pops and new biological pops.  Growth for the new bio pops seemed to start and stop each month: a new pop would be selected, grow for a month, then disappear with all the growth until a new pop was selected the following month.  Only by forcing the planet to grow my founding/primary species was I able to get around the issue.  Pops from migration treaties and a pop I uplifted would not grow even if forced, but would grow on established worlds for some reason.

**Comment by gebnar** [comment] 2019-12-03 18:12
Well... That rules out basically all the ideas I had before. I'm now suspecting it's something to do with species rights or living standards. Have you tried changing those around at all to see if it affects things?

**Comment by gebnar** [comment] 2019-12-03 18:58
If you're willing to put a bit more effort into tracking this down, I think the next step would be to post a savegame where this issue is happening into the mod discord. Then I can load it up and test to see what may be causing the issue.

**Comment by Lexalopolis** [comment] 2019-12-03 20:10
At the time I checked on all the species rights and living standards and they were set to the same thing.  One thing that comes to mind is that I believe the problems started after I took The Flesh is Weak perk and everyone converted to cyborgs, so that might have been part of it.  I did change reproductive rights from full to none and that did not appear to fix the issue.

I will try and grab a save game later and toss it in Discord so you can take a look, I appreciate the effort to try and think through what might be causing the issue!

**Comment by Lexalopolis** [comment] 2019-12-04 03:46
Sorry, I looked at my save files and unfortunately I was mostly using autosaves, and the only saves I have are from much earlier in my game before I settled the problematic worlds and from after I took synthetic ascension and all my pops became synths.  I'll keep an eye out and see if the bug shows up in other games, and if I do see it I'll grab a save file for you.

**Comment by gebnar** [comment] 2019-12-04 04:00
Have a look at the gebnar branch too. I've done a bunch of misc. fixes and
got the new ai code working (I think). If you're not in a rush, the changes
might hit staging tomorrow.

In the meantime, I can say I don't think I've fixed anything that would
have caused this issue. I'll keep an eye out for it in my ai tests though!

**Comment by gebnar** [comment] 2019-12-04 18:56
Ok. All of my changes are on Staging.
The AI planet specialization should work now.
Planet things cost minerals instead of alloys.
Farmers produce less food.
Misc. Migration script fixes.

None of these things are related to this issue. But I have been unable to reproduce this problem in any of my tests on this version.

One last thought. Did you update the mod at some point during the game where this issue occurred? It's possible something minor about pops changed and caused the engine to die in a fire... Try starting up a new game if you test out the new staging branch - and if you get the issue, post a save for me!

**Comment by Lexalopolis** [comment] 2019-12-04 20:43
That's a good thought, the mod may have updated and the issue started after that.  I am using the Steam version so an update may have pushed through and I didn't notice.  Glad the issue isn't showing up anywhere else though!  If I see it again I will let you know.

**Comment by gebnar** [comment] 2020-03-28 12:42
Closing, as this issue hasn't bee reported in a while, and seems to have been situational.

If it appears again, please re-open the issue!

**Closed by gebnar** 2020-03-28 12:42 UTC
